version: '3.8' # optional since v1.27.0
services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db:/var/lib/postgressql/data
volumes:
  db:
    driver: local
